# Generated by Django 2.2.16 on 2021-09-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210912_1846'),
        ('reviews', '0002_auto_20210911_2345'),
    ]

    operations = [
    ]
